/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminTablasTablaserverImport } from './routes/admin/tablas/tablaserver'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const LoginIndexLazyImport = createFileRoute('/login/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const AdminTablasTablaserverRoute = AdminTablasTablaserverImport.update({
  id: '/admin/tablas/tablaserver',
  path: '/admin/tablas/tablaserver',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/tablas/tablaserver': {
      id: '/admin/tablas/tablaserver'
      path: '/admin/tablas/tablaserver'
      fullPath: '/admin/tablas/tablaserver'
      preLoaderRoute: typeof AdminTablasTablaserverImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexLazyRoute
  '/admin/tablas/tablaserver': typeof AdminTablasTablaserverRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexLazyRoute
  '/admin/tablas/tablaserver': typeof AdminTablasTablaserverRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexLazyRoute
  '/admin/tablas/tablaserver': typeof AdminTablasTablaserverRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/login' | '/admin/tablas/tablaserver'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/login' | '/admin/tablas/tablaserver'
  id: '__root__' | '/' | '/admin/' | '/login/' | '/admin/tablas/tablaserver'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  AdminTablasTablaserverRoute: typeof AdminTablasTablaserverRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminIndexRoute: AdminIndexRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  AdminTablasTablaserverRoute: AdminTablasTablaserverRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin/",
        "/login/",
        "/admin/tablas/tablaserver"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/admin/tablas/tablaserver": {
      "filePath": "admin/tablas/tablaserver.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
